### ISSUE TITLE
Register common lints in workspace-level lint section

### ISSUE THREAD

**Issue by ChristopherBiscardi** [rust-adventure/bevy-examples#11]
Rust 1.74 allows specifying lints in a workspace-level `Cargo.toml`.

Common lints that Bevy applications trigger in clippy **but are typically false flags** are:

* [clippy::type_complexity](https://rust-lang.github.io/rust-clippy/master/#/type_comple)
* [clippy::too_many_arguments](https://rust-lang.github.io/rust-clippy/master/#/too_many_arguments)

Lints can be defined at the workspace `Cargo.toml`.

```toml
[workspace]
members = ["examples/*"]
resolver = "2"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"
```

Each package needs this in `Cargo.toml`.

```toml
[lints]
workspace = true
```
